# Generated by Django 6.0.7 on 2026-07-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=150)),
                ('content_en', models.TextField(blank=True)),
                ('content_sw', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_country', models.CharField(default='Unknown', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_meet_link', models.URLField(default='https://meet.google.com/', max_length=500)),
                ('daily_verse_en', models.TextField(default='For God so loved the world, that he gave his only Son, that whoever believes in him should not perish but have eternal life. - John 3:16')),
                ('daily_verse_sw', models.TextField(default='Kwa maana jinsi hii Mungu aliupenda ulimwengu, hata akamtoa Mwanawe pekee, ili kila mtu amwaminiye asipotee, bali awe na uzima wa milele. - Yohana 3:16')),
                ('prayer_time_utc', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=150)),
                ('content_en', models.TextField(blank=True)),
                ('content_sw', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_country', models.CharField(default='Unknown', max_length=100)),
            ],
        ),
    ]
