# Generated by Django 6.0.7 on 2026-07-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200)),
                ('title_sw', models.CharField(max_length=200)),
                ('content_en', models.TextField()),
                ('content_sw', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='airtel_lipa_namba',
            field=models.CharField(blank=True, default='112233', max_length=50),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='bank_account_name',
            field=models.CharField(blank=True, default='POWER REQUEST GROUP', max_length=150),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='bank_account_number',
            field=models.CharField(blank=True, default='0152435467800', max_length=100),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='bank_name',
            field=models.CharField(blank=True, default='CRDB Bank', max_length=150),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='mpesa_lipa_namba',
            field=models.CharField(blank=True, default='552211', max_length=50),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='paypal_link',
            field=models.CharField(blank=True, default='https://paypal.me/powerrequest', max_length=500),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='tigopesa_lipa_namba',
            field=models.CharField(blank=True, default='443322', max_length=50),
        ),
    ]
