# Generated by Django 6.0.7 on 2026-07-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_announcement_systemsetting_airtel_lipa_namba_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('title_en', models.CharField(max_length=150)),
                ('title_sw', models.CharField(max_length=150)),
                ('bio_en', models.TextField()),
                ('bio_sw', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='leaders/')),
                ('order', models.IntegerField(default=0)),
            ],
        ),
    ]
