# Generated by Django 6.0.7 on 2026-07-18 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_follower'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text_en', models.CharField(max_length=500)),
                ('question_text_sw', models.CharField(max_length=500)),
                ('correct_answer', models.CharField(help_text='The expected correct answer', max_length=200)),
                ('active_date', models.DateField(help_text='The date this question is shown', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField(default=False)),
                ('time_taken_seconds', models.FloatField(default=0.0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.follower')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.dailyquestion')),
            ],
            options={
                'unique_together': {('follower', 'question')},
            },
        ),
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.follower')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.dailyquestion')),
            ],
            options={
                'unique_together': {('follower', 'question')},
            },
        ),
    ]
