# Generated by Django 6.0.7 on 2026-07-18 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_dailyquestion_participantanswer_quizsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyquestion',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='participantanswer',
            name='answer_text',
        ),
        migrations.RemoveField(
            model_name='participantanswer',
            name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='participantanswer',
            name='time_taken_seconds',
        ),
        migrations.AddField(
            model_name='dailyquestion',
            name='correct_option',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='dailyquestion',
            name='option_a',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AddField(
            model_name='dailyquestion',
            name='option_b',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AddField(
            model_name='dailyquestion',
            name='option_c',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AddField(
            model_name='dailyquestion',
            name='option_d',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AddField(
            model_name='participantanswer',
            name='selected_option',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='dailyquestion',
            name='active_date',
            field=models.DateField(help_text='The date this question is shown'),
        ),
        migrations.CreateModel(
            name='DailyQuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_date', models.DateField()),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('time_taken_seconds', models.FloatField(default=0.0)),
                ('score', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.follower')),
            ],
            options={
                'unique_together': {('follower', 'active_date')},
            },
        ),
        migrations.DeleteModel(
            name='QuizSession',
        ),
    ]
