# Generated by Django 6.0.7 on 2026-07-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_remove_dailyquestion_correct_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyquestion',
            name='option_a',
        ),
        migrations.RemoveField(
            model_name='dailyquestion',
            name='option_b',
        ),
        migrations.RemoveField(
            model_name='dailyquestion',
            name='option_c',
        ),
        migrations.RemoveField(
            model_name='dailyquestion',
            name='option_d',
        ),
        migrations.AddField(
            model_name='dailyquestion',
            name='option_a_en',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AddField(
            model_name='dailyquestion',
            name='option_a_sw',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AddField(
            model_name='dailyquestion',
            name='option_b_en',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AddField(
            model_name='dailyquestion',
            name='option_b_sw',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AddField(
            model_name='dailyquestion',
            name='option_c_en',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AddField(
            model_name='dailyquestion',
            name='option_c_sw',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AddField(
            model_name='dailyquestion',
            name='option_d_en',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AddField(
            model_name='dailyquestion',
            name='option_d_sw',
            field=models.CharField(default='-', max_length=200),
        ),
    ]
