# Generated by Django 6.0.7 on 2026-07-20 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_remove_dailyquestion_option_a_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(blank=True, default='Anonymous', max_length=200, null=True)),
                ('donor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='TZS', max_length=10)),
                ('country', models.CharField(default='Tanzania', help_text='Country where the offering came from', max_length=100)),
                ('payment_method', models.CharField(choices=[('MPESA', 'M-Pesa'), ('TIGOPESA', 'Tigo Pesa'), ('AIRTEL', 'Airtel Money'), ('BANK', 'Bank Transfer'), ('CARD', 'Credit/Debit Card (Flutterwave/Stripe)'), ('PAYPAL', 'PayPal'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=200, null=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('date_received', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CountryLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(help_text='Country this leader manages (e.g. Kenya, USA)', max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leader_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
