# Generated by Django 6.0.7 on 2026-07-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_offering_countryleader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='email',
        ),
        migrations.AddField(
            model_name='follower',
            name='gender',
            field=models.CharField(choices=[('M', 'Male (Mwanaume)'), ('F', 'Female (Mwanamke)'), ('O', 'Other (Nyingine)')], default='M', max_length=1),
        ),
    ]
