# Generated by Django 6.0.7 on 2026-07-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_remove_follower_email_follower_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='merchant_reference',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='offering',
            name='order_tracking_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='offering',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='offering',
            name='payment_method',
            field=models.CharField(choices=[('MPESA', 'M-Pesa'), ('TIGOPESA', 'Tigo Pesa'), ('AIRTEL', 'Airtel Money'), ('BANK', 'Bank Transfer'), ('CARD', 'Credit/Debit Card (Flutterwave/Stripe)'), ('PAYPAL', 'PayPal'), ('PESAPAL', 'PesaPal (Mobile/Card)'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
    ]
