# Generated by Django 6.0.7 on 2026-07-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_offering_merchant_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='pesapal_ipn_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
